version: '2'
services:
   db:
    image: linuxserver/mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /portainer/AppData/Wordpress/DB:/config
    restart: unless-stopped
   wordpress:
     image: wordpress:latest
     ports:
      - "${WP_PORT}:80"
     restart: always
     environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
     working_dir: /var/www/html
     volumes:
      - /portainer/AppData/Wordpress/wp-content:/var/www/html/wp-content
